zend_extension = xdebug

[XDebug]
; run `make restart` if you change modes.
; phpstorm => tools => Analyze Xdebug Profiler Snapshot => docker\cachegrind.out.***.gz
xdebug.mode = debug
;xdebug.mode=profile
xdebug.output_dir = /var/www/docker
xdebug.client_host = host.docker.internal
xdebug.log = /var/www/docker/xdebug.log
xdebug.log_level = 3
xdebug.start_with_request = Yes
